# PyTorch Tensor Operations

In [4]:
import torch

## Arithmetic Element-wise Operations

In [20]:
a = torch.FloatTensor([[100, 2],
                       [3, 4]])
b = torch.FloatTensor([[2, 2],
                       [3, 3]])

In [11]:
a + b

tensor([[102.,   4.],
        [  6.,   7.]])

In [12]:
a - b

tensor([[98.,  0.],
        [ 0.,  1.]])

In [13]:
a * b

tensor([[200.,   4.],
        [  9.,  12.]])

In [14]:
a / b

tensor([[50.0000,  1.0000],
        [ 1.0000,  1.3333]])

In [15]:
a == b

tensor([[False,  True],
        [ True, False]])

In [16]:
a != b

tensor([[ True, False],
        [False,  True]])

In [ ]:
a ** b

tensor([[ 1.,  4.],
        [27., 64.]])

## Inplace Operations

In [22]:
print(a)
print(a.mul(b)) #a*b와 같음
print(a)
print(a.mul_(b)) #언더바 사용해서 a를 바꿔줌
print(a)

tensor([[200.,   4.],
        [  9.,  12.]])
tensor([[400.,   8.],
        [ 27.,  36.]])
tensor([[200.,   4.],
        [  9.,  12.]])
tensor([[400.,   8.],
        [ 27.,  36.]])
tensor([[400.,   8.],
        [ 27.,  36.]])


## Sum, Mean (Dimension Reducing Operations)

In [23]:
x = torch.FloatTensor([[1, 2],
                       [3, 4]])

In [24]:
print(x.sum())
print(x.mean())

tensor(10.)
tensor(2.5000)


In [25]:
print(x.sum(dim=0))
print(x.sum(dim=-1))

tensor([4., 6.])
tensor([3., 7.])


## Broadcast in Operations (모양이 다른 텐서끼리의 연산)

What we did before,

In [26]:
x = torch.FloatTensor([[1, 2]])
y = torch.FloatTensor([[4, 8]])

print(x.size())
print(y.size())

torch.Size([1, 2])
torch.Size([1, 2])


In [27]:
z = x + y
print(z)
print(z.size())

tensor([[ 5., 10.]])
torch.Size([1, 2])


**Broadcast feature provides operations between different shape of tensors.**

### Tensor + Scalar

In [28]:
x = torch.FloatTensor([[1, 2],
                       [3, 4]])
y = 1

print(x.size())

torch.Size([2, 2])


In [29]:
z = x + y
print(z)
print(z.size())

tensor([[2., 3.],
        [4., 5.]])
torch.Size([2, 2])


### Tensor + Vector

In [30]:
x = torch.FloatTensor([[1, 2],
                       [4, 8]])
y = torch.FloatTensor([3,
                       5])

print(x.size())
print(y.size())

torch.Size([2, 2])
torch.Size([2])


In [31]:
z = x + y
print(z)
print(z.size())

tensor([[ 4.,  7.],
        [ 7., 13.]])
torch.Size([2, 2])


In [32]:
x = torch.FloatTensor([[[1, 2]]])
y = torch.FloatTensor([3,
                       5])

print(x.size())
print(y.size())

torch.Size([1, 1, 2])
torch.Size([2])


In [33]:
z = x + y
print(z)
print(z.size())

tensor([[[4., 7.]]])
torch.Size([1, 1, 2])


### Tensor + Tensor

In [34]:
x = torch.FloatTensor([[1, 2]])
y = torch.FloatTensor([[3],
                       [5]])

print(x.size())
print(y.size())

torch.Size([1, 2])
torch.Size([2, 1])


In [35]:
z = x + y
print(z)
print(z.size())

tensor([[4., 5.],
        [6., 7.]])
torch.Size([2, 2])


Note that you need to be careful before using broadcast feature.

### Failure Case

In [ ]:
x = torch.FloatTensor([[[1, 2],
                        [4, 8]]])
y = torch.FloatTensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])

print(x.size()) # (1,2,2)
print(y.size()) #사이즈 자체가 (3,3)이어서 1을 어디에 넣어도 맞출 순 없음

z = x + y 